CREATE TABLE PRODUTOS_SERGEL(
    codigo NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    qtd NUMBER(10) NOT NULL,
    data_de_chegada DATE NOT NULL
);

SELECT * 
FROM PRODUTOS_SERGEL
WHERE QTD > 0;

UPDATE PRODUTOS_SERGEL
SET qtd = 2
WHERE codigo in ( 27,38,48,98,20,21);
COMMIT;

DROP TABLE PRODUTOS_SERGEL;