CREATE TABLE PRODUTOS_SERGEL(
    codigo NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    qtd NUMBER(10) NOT NULL
);

SELECT * 
FROM PRODUTOS_SERGEL
WHERE QTD > 0;

UPDATE PRODUTOS_SERGEL
SET qtd = 1
WHERE codigo in (1,2,3,4,5,6,7,8,9,10);
COMMIT;